import { NextPage } from "next"
import Head from "next/head"
import React from "react"

const Collections: NextPage = () => {
   return (
      <>
         <Head>
            <meta name="description" content="Generated by create next app" />
            <title>Loiro | Collections</title>
         </Head>

         <div>Collections</div>
      </>
   )
}

export default Collections
