import { NextPage } from "next"
import Head from "next/head"
import React from "react"

const Products: NextPage = () => {
   return (
      <>
         <Head>
            <meta name="description" content="Generated by create next app" />
            <title>Loiro | Products</title>
         </Head>

         <div>Products</div>
      </>
   )
}

export default Products
