import type { NextPage, GetStaticProps } from "next"
import Head from "next/head"
import client from "@lib/config/apollo"
import { GET_PRODUCTS } from "@lib/gql/queries/getProducts"
import { GET_CATEGORIES } from "@lib/gql/queries/getData"
import { Category, Product } from "types"

import Collection from "@components/sections/Collection"
import FilterGallery from "@components/sections/FilterGallery"
import HeroSlide from "@components/sections/HeroSlide"
import InstagramFeeds from "@components/sections/InstagramFeeds"
import Policy from "@components/sections/Policy"
import ProductList from "@components/sections/ProductList"
import ShopByCategory from "@components/sections/ShopByCategory"
import Newsletter from "@components/Shared/Newsletter"

interface HomePropTypes {
   categories: Category[]
   products: Product[]
}

const Home: NextPage<HomePropTypes> = ({ categories, products }) => {
   return (
      <>
         <Head>
            <meta name="description" content="Generated by create next app" />
            <title>Loiro | Home</title>
         </Head>

         <section className="w-full max-h-[680px]">
            <HeroSlide />
         </section>

         <section className="">
            <Collection />
         </section>

         <section className="mt-28">
            <ProductList products={products} title="New Arrivals" />
         </section>

         <section className="mt-28">
            <ShopByCategory categories={categories} />
         </section>

         <section className="mt-28">
            <FilterGallery products={products} />
         </section>

         <section className="mt-20">
            <InstagramFeeds />
         </section>

         <section className="mt-20">
            <Newsletter />
         </section>

         <section className="mt-20">
            <Policy />
         </section>
      </>
   )
}

export const getStaticProps: GetStaticProps = async () => {
   const { data: category } = await client.query({ query: GET_CATEGORIES })
   const { data: products } = await client.query({ query: GET_PRODUCTS })

   return {
      props: {
         categories: category.Categories,
         products: products.products,
      },
   }
}

export default Home
